// One-off generator: builds src/sim/names.ts with 1000 real German first names
// and 1000 surnames. Sources: curated common core (already in dist) + the
// PyZufall name lists (fetched to /tmp). Run: node scripts/gen-names.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { FIRST_NAMES as CURATED_FIRST, LAST_NAMES as CURATED_LAST } from '../dist/sim/names.js';

const BLOCK = new Set([
  // junk entries in the source list
  'Asdg', 'Banane', 'Birne', 'Gurke', 'Po', 'M.',
  // historically heavily-loaded surnames — out of place in a lighthearted game
  'Hitler', 'Himmler', 'Goering', 'Göring', 'Goebbels', 'Heydrich', 'Mengele', 'Eichmann', 'Bormann',
]);
const valid = (n) => n.length >= 3 && /^[A-ZÄÖÜ][A-Za-zÄÖÜäöüß'-]+$/.test(n) && !BLOCK.has(n);

const lines = (f) => readFileSync(`/tmp/${f}`, 'utf8').split('\n').map((s) => s.trim()).filter(Boolean);

// Deterministic shuffle (seeded Fisher–Yates) so generation is reproducible.
function shuffle(arr, seed) {
  const a = arr.slice();
  let s = seed >>> 0;
  const rnd = () => ((s = (s * 1664525 + 1013904223) >>> 0) / 4294967296);
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rnd() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function build(curated, webNames, seed) {
  const seen = new Set();
  const out = [];
  // Curated common names first (guarantees the everyday names are in), then a
  // shuffled spread of the big web list for variety across the alphabet.
  for (const n of [...curated, ...shuffle(webNames, seed)]) {
    if (!valid(n) || seen.has(n)) continue;
    seen.add(n);
    out.push(n);
    if (out.length === 1000) break;
  }
  if (out.length < 1000) throw new Error(`only ${out.length} names, need 1000`);
  return out.sort((a, b) => a.localeCompare(b, 'de'));
}

const first = build(CURATED_FIRST, [...lines('vornamen_m.txt'), ...lines('vornamen_w.txt')], 12345);
const last = build(CURATED_LAST, lines('nachnamen.txt'), 67890);

const fmt = (arr) => {
  const rows = [];
  for (let i = 0; i < arr.length; i += 10) {
    rows.push('  ' + arr.slice(i, i + 10).map((n) => `'${n.replace(/'/g, "\\'")}'`).join(', ') + ',');
  }
  return rows.join('\n');
};

const file = `// Name pools for guests. Real, common German first names and surnames — every
// guest gets a random first + last name. 1000 of each (curated common core +
// the PyZufall name lists), so full names effectively never repeat in a session.
// Generated by scripts/gen-names.mjs.

export const FIRST_NAMES: readonly string[] = [
${fmt(first)}
];

export const LAST_NAMES: readonly string[] = [
${fmt(last)}
];
`;

writeFileSync('src/sim/names.ts', file);
console.log(`wrote ${first.length} first names, ${last.length} surnames`);
